name: Rust

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '11 7 * * 1,4'

env:
  RUSTFLAGS: -Dwarnings

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run cargo fmt
        run: |
          cargo fmt --all -- --check
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run cargo clippy
        run: |
          cargo clippy --workspace --tests --examples
  docs:
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -Dwarnings
    steps:
      - uses: actions/checkout@v2
      - name: Run cargo clippy
        run: |
          cargo doc --workspace --no-deps
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Run cargo test
        run: |
          cargo test --workspace

  installer-path-setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            install-expr: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/Gankra/cargodisttest/releases/download/v0.20.2/cargodisttest-installer.sh | sh
            check-path: echo "$PATH"
            check-gh-path: cat "$GITHUB_PATH"
          - os: macos-latest
            install-expr: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/Gankra/cargodisttest/releases/download/v0.20.2/cargodisttest-installer.sh | sh
            check-path: echo "$PATH"
            check-gh-path: cat "$GITHUB_PATH"
          - os: windows-latest
            install-expr: powershell -c "irm https://github.com/Gankra/cargodisttest/releases/download/v0.20.2/cargodisttest-installer.ps1 | iex"
            check-path: echo "$env:PATH"
            check-gh-path: cat "$env:GITHUB_PATH"
    steps:
      - name: precheck PATH
        run: ${{ matrix.check-path }}
      - name: precheck GH_PATH
        run: ${{ matrix.check-gh-path }}
      - name: install cargodisttest
        run: ${{ matrix.install_dist }}
      - name: postcheck PATH
        run: ${{ matrix.check-path }}
      - name: postcheck GH_PATH
        run: ${{ matrix.check-gh-path }}
      - name: use cargodisttest
        run: cargodisttest --version
          
